### ISSUE TITLE
add `serialize` and `deserialize` functions to `diesel-wasm-sqlite` backend

### ISSUE THREAD

**Issue by insipx** [xmtp/libxmtp#1003]
Serialize docs: https://sqlite.org/c3ref/serialize.html
Deserialize docs: https://sqlite.org/c3ref/deserialize.html
SQLite WASM: https://www.sqlite.org/wasm
sqlite3 WebAssembly C-Style API documentation: https://www.sqlite.org/wasm/doc/trunk/api-c-style.md
`wasm-bindgen` (rust -> js ffi) docs: https://rustwasm.github.io/wasm-bindgen/reference/attributes/on-js-imports/index.html 

the `serialize` and `deserialize` methods on `RawConnection` are commented out:
https://github.com/xmtp/libxmtp/blob/bb18b61df2e310b7c23ad222cb2c167fa9b28ae9/diesel-wasm-sqlite/src/connection/raw.rs#L89

They still use the raw C-bindings from `libsqlite3-sys` rust crate. We want to convert these to use the WASM bindings.

- Add the required methods to `ffi.rs` and `package.json` for serialize/deserialize
- add the methods to `raw.rs`

**Comment by vking45** [comment]
Hey, I would like to work on this issue. Can you please assign this issue to me ?

**Comment by codabrink** [comment]
Picking up this issue where @vking45 left off.
