### ISSUE TITLE
failed to create group from welcome: storage error: Diesel result error: welcome id already exists

### ISSUE THREAD

**Issue by nplasterer** [xmtp/libxmtp#1025]
failed to create group from welcome: storage error: Diesel result error: welcome id already exists

Getting this error randomly on iOS and Android when trying to stream messages to a group. 

Steps:
Create Group
Start Stream All Messages
Send message to group
Cancel Stream All Message
Send message to group
Start Stream All Messages
Send message to group 💥  --> blows up with `welcome id already exists`

This feels odd since no welcome should be getting created at this point?

**Comment by nplasterer** [comment]
Seems suspicious that the group ids wouldn't match for a group that clearly exists. 🤔 

https://github.com/xmtp/libxmtp/blob/main/xmtp_mls/src/storage/encrypted_store/group.rs#L224-L229

**Comment by nplasterer** [comment]
Test still pass so probably not a huge deal.

**Comment by neekolas** [comment]
Could happen if we are trying to process the same welcome more than one time.

**Comment by nplasterer** [comment]
Maybe this should be a warning instead of a error.
