### ISSUE TITLE
Make clear distinctions between DMs & Groups with common Conversation

### ISSUE THREAD

**Issue by nplasterer** [xmtp/libxmtp#1130]
With DMs being a group under the hood I'm afraid the lines between the two are going to get increasingly more confusing and potentially cause bugs. 
To make this easier I think we should make very clear distinctions between DMs and Groups with a common interface of Conversation when doing both in the bindings.

Here are some functions that should exist
- [x] listGroups - (filters groups on NOT type dm)
- [x] listDms - (filters groups on type dm)
- [x] listConversations - (no filter aka dms and groups)
- [x] streamGroups
- [x] streamDms
- [x] streamConversations
- [x] findConversation(id) - (probably no longer need the findGroup method)
- [x] consentType - (GROUP_ID, INBOX_ID, ADDRESS) should be -> (CONVERSATION_ID, INBOX_ID, ADDRESS)
- [x] streamAllGroupMessages -> we need this in the dualsending interim when we don't want to stream dm groups
- [x] streamAllDMMessages -> we need this in the dualsending interim when we don't want to stream dm groups
- [x] streamAllMessages -> this will be used to stream all messages in a V3 only world

**Comment by richardhuaaa** [comment]
This sounds great to me. Do any of these involve breaking changes to the meaning of existing methods?

**Comment by nplasterer** [comment]
I don't think there is enough meaningful data in the local consent database to warrent a major issue with renaming `GROUP_ID` to `CONVERSATION_ID` but that would be the only breaking change.
