### ISSUE TITLE
Disable metadata in DMs

### ISSUE THREAD

**Issue by nplasterer** [xmtp/libxmtp#1169]
I think for simplicity's sake we shouldn't enable these for DM's. That smooths over compatibility issues with V2, as well as issues involved in deduplicating DM's with different metadata in V3. Would recommend disabling it in libxmtp too

_Originally posted by @richardhuaaa in https://github.com/xmtp/xmtp-android/pull/307#discussion_r1811246279_

**Comment by neekolas** [comment]
Great. I'd suggest all V2 convos with different conversation IDs get collapsed into one v3 convo on import.
