### ISSUE TITLE
Bug: FfiMessage has no available properties

### ISSUE THREAD

**Issue by nakajima** [xmtp/libxmtp#211]
### Describe the bug

There's no way to access data about an FfiMessage such as content or sender address.

See https://github.com/xmtp/libxmtp-swift/blob/main/Sources/LibXMTP/xmtpv3.swift#L661-L676.

**Comment by neekolas** [comment]
Ahhh. I see what I did wrong in the bindings. They need to be derived as `uniffi::Record` instead of `uniffi::Object`, then it will expose the fields in the generated Kotlin/Swift code.

**Comment by nakajima** [comment]
Gotcha, I tried making that change but was met with some errors I couldn't decipher:

<img width="1481" alt="image" src="https://github.com/xmtp/libxmtp/assets/483/43da8c2d-1fa0-4d31-9df7-b6e1316fabb4">

**Comment by nakajima** [comment]
Ok, I was able to get fields working for messages, but trying to derive `uniffi:Record` for objects that reference a client don't seem to work. So for example, when I attempted to add an `id` field to  `FfiConversation`, I ran into 

<img width="1582" alt="image" src="https://github.com/xmtp/libxmtp/assets/483/f3c07884-0ced-4353-953f-7e03c1224757">

**Comment by nakajima** [comment]
I tried removing the `Arc<>` wrappers around the `RustXmtpClient` but it doesn't seem like the underlying type works either.

**Comment by neekolas** [comment]
I think the answer is just to keep those ones as `Object` and create accessor methods to get at the data.

**Comment by nakajima** [comment]
Fixed in https://github.com/xmtp/libxmtp/pull/215.
