### ISSUE TITLE
Feature request: Add way to identify FFiConversation

### ISSUE THREAD

**Issue by nakajima** [xmtp/libxmtp#212]
### Is your feature request related to a problem?

It would be nice to have a way to identify a conversation. I'd say "peer address" though in a world with group chat, that makes less sense. Maybe topic info?

https://github.com/xmtp/libxmtp-swift/blob/main/Sources/LibXMTP/xmtpv3.swift#L399C36-L463

**Comment by neekolas** [comment]
Great call out. We have an internal identifier `convo_id` (not to be confused with V2 conversation IDs) that feels like it would do what you want. It's just the sorted member list right now, but it's treated as an opaque string in `libxmtp` and might be produced in different ways for things like group conversations.

**Comment by nakajima** [comment]
Exposed `convo_id` in https://github.com/xmtp/libxmtp/pull/215
