### ISSUE TITLE
Feature request: `topic_refresh_state` database table

### ISSUE THREAD

**Issue by neekolas** [xmtp/libxmtp#292]
### Is your feature request related to a problem?

We need some database methods for interacting with the `topic_refresh_state`.

- [x] `Store` and `Fetch` trait implementations
- [ ] `lock_topic`
- [ ] `unlock_topic` method on `EncryptedMessageStore`

### Describe the solution to the problem

The way this needs to work is that we want to lock the row for a given topic while we are loading messages from it, and unlock the row when the job is complete.

We could use a pessimistic locking strategy, like wrapping updates in a transaction or otherwise locking the database. But we don't want to block read access for that long given we are waiting for asynchronous network requests to complete.

So, it may make more sense to just add a `locked_until` field on the table which we can use to do concurrency control. The way that would work would look something like this:

When we begin a refresh of the topic we would use the `lock_topic` method to check the current row and ensure that it either
A) Doesn't exist
B) Has a `locked_until` value set in the past

If the check fails (the topic is currently locked) we would retry in a loop until it becomes unlocked. If either of the conditions above are true, we would continue to set the `locked_until` value to something like 5 or 10 seconds into the future.

When the operation has completed we would update the row and set the `locked_until` value to NULL using the `unlock_topic` method and set the `last_message_timestamp_ns` field to the timestamp of the newest entry in the topic (if any). These two operations should be done in the same database update. 

### Additional details

I'm open to other implementations that give us the same properties.

1. We don't completely lock up the database to other callers while the topic refresh job is in progress
2. We can ensure a single process is refreshing a given topic at any time
3. The `last_message_timestamp_ns` field is updated at the same time or before the topic is unlocked for the next caller

I'm open to solutions that just use application-level mutexes to get to the same result, which would be fine given that we expect only a single `libxmtp` instance will be operating on a database at any time.

**Comment by insipx** [comment]
I also think it would be possible to use a `RWLock` here and enforce updates in a single thread

**Comment by richardhuaaa** [comment]
@insipx I wrote up a possible method for handling concurrency here: https://github.com/xmtp/libxmtp/pull/284. The advantage is it's relatively simple to implement and non-blocking for callers. Would love your thoughts!
