### ISSUE TITLE
When joining a group from a welcome, members should update their keys before sending the first message

### ISSUE THREAD

**Issue by neekolas** [xmtp/libxmtp#347]

**Comment by richardhuaaa** [comment]
Broader validation checklist: https://www.rfc-editor.org/rfc/rfc9420.html#name-credential-validation

**Comment by lfzkoala** [comment]
I think this issue has become key updating not only joining a group from welcome, but also key updating before every new group intent that I did in https://github.com/xmtp/libxmtp/pull/658 and mentioned in https://xmtp-labs.slack.com/archives/C05GBHEAGPP/p1713302830615839
