### ISSUE TITLE
iOS bindings [EthDenver]

### ISSUE THREAD

**Issue by richardhuaaa** [xmtp/libxmtp#365]

**Comment by neekolas** [comment]
We talked about listing out the functions needed in the wrapped client SDKs. I'll take a stab at it here with this total pseudocode that should in no way be treated as an API spec. 

## General
- `create_client` to create a V3 client

## Client methods
- `account_address() -> String`
- `installation_id() -> []byte`
- `conversations() -> Conversations`
- `register_identity()`. This one is required today, although we are thinking about just making registration implicit on client creation. Shouldn't really be the callers job to figure out when to register.
- `list_my_installations() -> []Installation`. Not implemented, but will be required when we get to building revocation
- `revoke_installation()`. Not implemented. Will be required when we roll out revocation (which doesn't seem necessary for ETHDenver)

## Conversations methods
- `create_group() -> Conversation`
- `list() -> []Conversation`

## Conversation/Group methods
- `id() -> []byte` get the unique identifier for the conversation
- `send()`
- `sync()`
- `find_messages() -> []Message`
- `list_members() -> []ConversationMember`
- `add_members()`
- `remove_members()`
- `leave()`. Not implemented. Some way of leaving a conversation. What happens under the hood may change here as we improve the underlying implementation

**Comment by richardhuaaa** [comment]
Adding on things as I think of them:
- We may need a way to sync updates from all conversations (including welcomes, as well as for rendering an inbox view with snippets from all threads).
- There will be changes to the registration flow (e.g., a `preGrantMessagingAccess` callback), I'm working on that now

**Comment by richardhuaaa** [comment]
- We need to figure out how consent, pushability and hmac keys will be exposed for libxmtp

**Comment by neekolas** [comment]
> We need to figure out how consent, pushability and hmac keys will be exposed for libxmtp

Think that's a separate convo, which might flow back into here. I do have some ideas around pushability at least.

**Comment by nplasterer** [comment]
I added a tracking issue for this work in Kotlin so we can keep track of it as we do it. https://github.com/xmtp/xmtp-kotlin/issues/1

**Comment by neekolas** [comment]
Added one more item. Some sort of `can_message()`, since we need to be able to check if a user has a V3 identity.
