### ISSUE TITLE
Message send state

### ISSUE THREAD

**Issue by richardhuaaa** [xmtp/libxmtp#516]
Expose optimistic message sends.

Per conversation/request from a partner on April 10, when we do this work, let's make sure
`await group.send` returns the group id (it currently returns the message ID)

**Comment by nmalzieu** [comment]
Hey @richardhuaaa , it's the opposite :) It currently returns the group id but it should return the message id (as we already know the group id!)

**Comment by richardhuaaa** [comment]
Context: https://github.com/xmtp/libxmtp/issues/529

**Comment by richardhuaaa** [comment]
After https://github.com/xmtp/libxmtp/pull/544/files#diff-3a24c3e76565487a710ac9863ac05160128f4f90892e07849b555a6de43a6e8f, optimistic message sends will be returned when listing messages in a conversation, with delivery status UNPUBLISHED.

- We might need a way to get the delivery status of messages
- We could return the message ID from a message send, but unsure if it still matters here - the integrator doesn't need to manually create the optimistic message, it will be in the libxmtp DB
- The optimistic message will be returned when listing messages, but won't be returned on subscriptions until they are updated to PUBLISHED. Does this matter?

**Comment by richardhuaaa** [comment]
Naomi has a good Q: if the message send fails after 3 retries, do we delete the optimistic message?

**Comment by richardhuaaa** [comment]
Maybe in addition to UNPUBLISHED and PUBLISHED, we should have a FAILED status

**Comment by richardhuaaa** [comment]
Maybe add option to filter published/unpublished message

**Comment by nmalzieu** [comment]
> After https://github.com/xmtp/libxmtp/pull/544/files#diff-3a24c3e76565487a710ac9863ac05160128f4f90892e07849b555a6de43a6e8f, optimistic messages will be inserted into the libxmtp DB and returned to the integrator when listing messages in a conversation, with delivery status UNPUBLISHED.
> 
> * We might need a way to get the delivery status of messages
> * We could return the message ID from a message send, but unsure if it still matters here - the integrator doesn't need to manually create the optimistic message, it will be in the libxmtp DB
> * The optimistic message will be returned when listing messages, but won't be returned on subscriptions until they are updated to PUBLISHED. Does this matter?

Getting back the message id from `await group.send()` would still be useful, because as you said, the subscriptions won't return the message, but we need a way to display it immediatly, and for that we need its unique id (so that when it's published and we get it back through subscriptions, we recognize it and don't show duplicates in the UI)
