### ISSUE TITLE
Add permission level to Group

### ISSUE THREAD

**Issue by nplasterer** [xmtp/libxmtp#521]
We can now set the permission on the group create but we don't have a way to fetch what permission level this group has afterwards.

Can we add a new field to Group called `permissions` that returns a `GroupPermission`.

It may also be nice to add functionality to groups to change permission levels after create with a `updatePermissions` function but that's more a nice to have.

**Comment by neekolas** [comment]
Will add a way to show current permissions. 

The permissions model for a group is set in stone once the group is created, but we are going to add more permissions models that include flexible policies like "group admins can do X". Then the admin list will be mutable. 

Doing it that way makes the security model easier to reason about. Less room for funny-business if the core policies are immutable.

**Comment by nplasterer** [comment]
Another request is to be able to see who the group admin is. So maybe a field like `group_admin` that returns a member? Unless you think that information should be private then maybe just a `is_admin` to see if the person viewing is the admin.

**Comment by nmalzieu** [comment]
Also interested in knowing if it would be technically possible to validate that someone is the admin of a group in our backend? To add features for the admin out of the protocol (1st feature in mind : name the group before it's part of the protocol)

**Comment by insipx** [comment]
This seems to exist: https://github.com/xmtp/libxmtp/blob/0a3787f023de5b9de510c11dcb7625265597ca09/bindings_ffi/src/mls.rs#L1263
