### ISSUE TITLE
RN Crash points to rust panic - "timed out waiting for connection"

### ISSUE THREAD

**Issue by cameronvoell** [xmtp/libxmtp#531]
> Right now I’m able to make the app crash consistently when doin Client.createRandom:

```
thread 'async-compat/tokio-1' panicked at src/mls.rs:287:18:
called `Result::unwrap()` on an `Err` value: Storage(Pool("timed out waiting for connection"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace"
```

I believe this is the line
https://github.com/xmtp/libxmtp/blob/334ee4b558437d1baae25439d25d63eebd01ba9a/bindings_ffi/src/mls.rs#L287

**Comment by insipx** [comment]
I think we should have solved these
