### ISSUE TITLE
Move the inner encrypted welcome payload to a proto wrapper, so we can support additional fields

### ISSUE THREAD

**Issue by nplasterer** [xmtp/libxmtp#547]
Hard to migrate if we don't do this.

**Comment by insipx** [comment]
This seems like it exists and is versioned: https://github.com/xmtp/libxmtp/blob/0a3787f023de5b9de510c11dcb7625265597ca09/xmtp_proto/src/gen/xmtp.mls.api.v1.rs#L5

@nplasterer
