### ISSUE TITLE
Tracking: MLS WASM DB/Storage (Group Chat Prod - Web)

### ISSUE THREAD

**Issue by nplasterer** [xmtp/libxmtp#556]
We want `bindings_wasm` to expose a complete MLS client similar to how `bindings_ffi` exposes one for kotlin and swift. The biggest hurdle is figuring out the things that don't work the same between the two. 

- db/storage: the `xmtp_mls` bundles the storage system and we’ll need to provide a wasm-friendly implementation. Ideas considered thus far include:
    - backing it with indexedDB (upside: well supported, downside: poor match for the existing SQLite storage system)
    - using OPFS for SQLite in wasm (upside: direct-ish mapping to existing SQLite storage system, downside: newish, possibly less well supported)
    - https://developer.chrome.com/blog/sqlite-wasm-in-the-browser-backed-by-the-origin-private-file-system/
    - https://sqlite.org/wasm/doc/trunk/persistence.md#vfs-opfs

**Comment by irzhywau** [comment]
hi, any news about this ticket?

**Comment by insipx** [comment]
Hi @irzhywau !

This is currently in alpha, feel free to use the end-user SDK for MLS Group Chat in the browser [here](https://www.npmjs.com/package/@xmtp/browser-sdk)
