### ISSUE TITLE
Create test cases for ERC-1271 signature verification

### ISSUE THREAD

**Issue by neekolas** [xmtp/libxmtp#598]
We are going to need to test some new scenarios here. From the XIP

> If a user with valid installation keys rotates their signing method for their Smart Contract Wallet, installation key credentials inspected by others should still pass ERC-1271 signature validation.

> If an XMTP user with a Smart Contract Wallet has a signing method that is compromised, and then rotates away the compromised signing method, the compromised signing method should not be able to sign XMTP credentials that pass validation for more than the designated block_tolerance as described in the Specification section above.

**Comment by neekolas** [comment]
This feels like a good opportunity for mocking. Maybe we just get really good at mocking out the blockchain calls.

**Comment by 37ng** [comment]
> If an XMTP user with a Smart Contract Wallet has a signing method that is compromised, and then rotates away the compromised signing method, the compromised signing method should not be able to sign XMTP credentials that pass validation for more than the designated block_tolerance as described in the Specification section above.

To clarify, this compromised signing method will **still be able to** sign XMTP credentials within the designated block_tolerance?

**Comment by 37ng** [comment]
Also, it seems to me that `block_tolerance` is used to prevent a compromised expired key from signing a new association. Correct me if I'm wrong, but I don't think a expired key should be able to sign a new association regardless of compromised or not.
