### ISSUE TITLE
Migration and Rollout Strategy

### ISSUE THREAD

**Issue by nplasterer** [xmtp/libxmtp#650]
This needs to be discussed further.

My recommendation is to go ahead and ship all of the group features in the SDK (both sending and receiving), but ask our implementors to hide any UX behind a date flag (something like: `if date > target_date { groups_enabled = true }`).

The target date should be some amount of lead time AFTER the feature is shipped. This gives time for all apps in the ecosystem to implement groups, as well as for all users to update to apps that support groups. The target date should be selected so that we expect for example 90% of apps in production to be in a version that supports groups by this time.

It may be desirable for integrators to individually select their own target date, or alternatively for us to co-ordinate a target date between all of the integrators. If the latter we could add a function called `should_enable_groups()` or `target_date()` from the SDK that all integrators can call.

**Comment by nplasterer** [comment]
To be able to message users in a group the client needs to be created with a V3 identity. That means all users logged into V2 are not automatically messagable in group chats. I can see this going two ways
- First we enable V3 identities in the background for any new client created on the latest version even if the client doesnt support group chat. This means lots of clients in V2 only apps will still get the new V3 identity keys and be messagable in group chats. The biggest drawback to this is that people could start group chats with people who have no idea that they've been added to a group because they don't have a client that supports groups.
- Second we keep V3 identity creation behind the enable group chat flag. Which means only clients that opt in to the flag will create a V3 identity. This means that only people with a V3 identity will likely be people on an app that supports group chat. So people creating new group chats will know for certain if the person they are group chatting is in fact reachable or not. CanMessage will give an accurate picture of people that can be reached or not.

I could go either way on this issue. I can see value in getting more people onto V3 identities. But I can also see value in `canMessage` actually showing people that can be reached in a group chat.

cc @saulmc for a decision here

**Comment by saulmc** [comment]
>  The biggest drawback to this is that people could start group chats with people who have no idea that they've been added to a group because they don't have a client that supports groups.

This could actually create a positive competitive dynamic, where AppWithGroups can market to AppWithoutGroups' users that they have group messages waiting for them, thus pressuring AppWithoutGroups to move fast to ship groups.

> But I can also see value in canMessage actually showing people that can be reached in a group chat.

For sure. Maybe we could split up `canMessage` and `canGroupMessage` somehow? Is there any way we could tell apart V3 identities that have used V3 apps from ones still stuck in V2 apps?

**Comment by nplasterer** [comment]
> For sure. Maybe we could split up canMessage and canGroupMessage somehow? Is there any way we could tell apart V3 identities that have used V3 apps from ones still stuck in V2 apps?

If we go the route of creating V3 identity in the background even in apps that don't support groups we won't be able to tell.

**Comment by saulmc** [comment]
Dang. I was thinking of that as more of a nice-to-have anyway. And in the likely case that the first app to ship groups is one that we've built, we'll actually know from app data which v3 identities have groups and which don't. The app could even get cheeky and send a v2 message "you've been invited to a group, but you need to use an app with groups to access it"...

So: no, let's not gate v3 identity behind the enable group chat flag.

**Comment by saulmc** [comment]
Decided to allow v3 identity creation in apps without groups.

**Comment by nplasterer** [comment]
Reopening this just cause the decision will require us to remove the gates before release.

**Comment by richardhuaaa** [comment]
There are two levels of rollout required to support groups:
1. App developers need to upgrade XMTP in their app, and implement UI for groups
2. Users need to upgrade their version of the app to one in which groups is supported (and for example, a group may consist of half users who have upgraded, and half who have not, even if all users are on the same app)

To address (1), it seems the idea here is to create a competition dynamic to incentivize developers to create groups? To address (2), is our idea here to let developers figure out a strategy for handling this?

I'm just highlighting this because any interaction failure here will reflect negatively on the protocol.

**Comment by nplasterer** [comment]
I kind of agree here with Rich. I think a possibly better flow would be this:
<img width="1221" alt="Screenshot 2024-05-29 at 6 01 31 PM" src="https://github.com/xmtp/libxmtp/assets/3522670/f0d11f95-f8c6-4d69-b9c6-73c8e2bdfce0">

This would assume we keep group chat gated so that canMessageV3 stays true to the people who can actually be reached in a group chat. cc @richardhuaaa @saulmc

**Comment by saulmc** [comment]
Ooh, achieve the growth loop without creating ghost group members. Very happy to change my mind on this! Thanks.

**Comment by nplasterer** [comment]
Okay with this in mind then we will not be removing the gate and it will be just education to integrators on how to reach clients on V2 with notices of groups trying to be created in V3. And so in that case there is no work that needs to be done in the sdk and I actually think this can be closed/transferred to https://github.com/xmtp-labs/xmtp-inbox-mobile. 😄
