### ISSUE TITLE
Permissions - Ability to create a group chat that only has two members and cannot have additional members added (Medium)

### ISSUE THREAD

**Issue by nplasterer** [xmtp/libxmtp#694]
1:1 chats don’t need custom permissions IMO. All 1:1 chats should work the same way.

We should be able to use our existing permissions framework to enable 1:1. We’d just define a default permission set required on all 1:1 chats.

We may want to spend a bit of time making sure we don’t need to upgrade our permission system to support this permission set. Maybe there are some additional fields we can add now, even if they’re unused, to make room for 1:1. For example, an optional list of `allowed_members` on the `ImmutableMetadata` to restrict the group to 2 people.
	
	
	
	
- [ ] New permission type to identify a 1to1 conversations
- [ ] Way to handle adding just one person to the group after create (possibly and immutable list called allowed_members)
- [ ] Validation
  - [ ] 1to1 Group should not be able to be named
  - [ ] You cannot leave a 1to1 Group
  - [ ] Should not see a group membership change codec on first send

**Comment by cameronvoell** [comment]
Related PR - https://github.com/xmtp/libxmtp/pull/901
