### ISSUE TITLE
GroupUpdated Message Type

### ISSUE THREAD

**Issue by cameronvoell** [xmtp/libxmtp#712]
### Is your feature request related to a problem?

One thing that is going to have to change as part of the move to Inbox IDs is the GroupMembershipChanges transcript message that we write when someone is added or removed from the group. At the bare minimum we are going to need to make it reference inbox_id instead of account_address.

A GroupUpdated message type that would cover both membership changes as well as changes to the mutable metadata. We're going to need some way for apps to display the event that someone changed the group name/description/admin roles, and it feels like the appropriate place.

**Comment by insipx** [comment]
Looking at `IntentKind` enum, this seems to have been added. Re-open if not @cameronvoell
