### ISSUE TITLE
Request wallet signature for identity key

### ISSUE THREAD

**Issue by richardhuaaa** [xmtp/libxmtp#74]
Need to define the Rust interface for requesting this. Additionally, sign the fallback key (using the identity key or the wallet key?)

**Comment by neekolas** [comment]
I would think the fallback key would be signed by the identity key, unless we have a strong reason to sign both with the wallet. Every user signature adds friction to the protocol and too many signatures encourages users to tune out and ignore them. We want wallet signatures to be rare enough that they demand attention

**Comment by jazzz** [comment]
#111 Adds support for associating EOAs to Accounts via signatures. The signing mechanism uses an AccountCreator which was designed to facilitate keySigning in wasm -- Wasm is not longer a target so, so a signer could be added in the future but doesn't seem pressing at the moment.
