### ISSUE TITLE
Bug: [XMTPRustSwift] swift files being included in Headers of XCFramework

### ISSUE THREAD

**Issue by michaelx11** [xmtp/libxmtp#83]
### Describe the bug

Need to exclude `*.swift` files from step that copies from `Generated` to `include`: https://github.com/xmtp/libxmtp/blob/main/bindings/xmtp_rust_swift/Makefile#L32

**Comment by tuddman** [comment]
Closing.
The referenced file in the description no longer exists.  FFI logic has been moved into `bindings_ffi/` and if there is a specific issue with swift, it is better to open a new issue in [this repo](https://github.com/xmtp/libxmtp-swift)
