### ISSUE TITLE
Hide identity logs

### ISSUE THREAD

**Issue by fabriguespe** [xmtp/libxmtp#853]
On every bot run im getting a long list of logs regarding identity.

![Image](https://github.com/xmtp/libxmtp/assets/1447073/2aaf825b-af68-4a22-8cae-69c9e4514f96)

**Comment by neekolas** [comment]
Ya. These are not very useful. We can ditch them.

**Comment by insipx** [comment]
I think this was fixed? @neekolas At least i can no longer find the log in libxmtp. Re-open if not
