### ISSUE TITLE
Removed members may still be able to send messages

### ISSUE THREAD

**Issue by richardhuaaa** [xmtp/libxmtp#900]
I suspect removed members can still send messages on a group, because all other members accept messages from previous epochs. The way we can test this is to write a unit test that removes a member, send a message to the group from the same member, and verify that the remover does not receive the message. We also need to verify that if the unit test passes, it's because there is logic on the receiver that is rejecting the message, not logic on the sender (which can be circumvented).

**Comment by nplasterer** [comment]
Looks like this test has been written.
