### ISSUE TITLE
Group error: Errors occurred during sync [NoChanges]

### ISSUE THREAD

**Issue by nplasterer** [xmtp/libxmtp#920]
:wave: We're getting an error thrown in converse `*LibXMTP.GenericError:* GroupError(message: "Group error: Errors occurred during sync [NoChanges]") (Code: 4)`
Am I understanding this error correctly. Is this throwing an error anytime there is no changes detected during a sync?
<https://github.com/xmtp/libxmtp/blob/main/xmtp_mls/src/groups/sync.rs#L129-L131>

[Slack Message](https://xmtp-labs.slack.com/archives/C05GBHEAGPP/p1721838179131139?thread_ts=1721838179.131139&cid=C05GBHEAGPP)

**Comment by nplasterer** [comment]
Curious if this is getting thrown here https://github.com/xmtp/libxmtp/blob/main/xmtp_mls/src/groups/sync.rs#L1172-L1175 Going to try and work on a reproduction test. 🙏

**Comment by nplasterer** [comment]
Possibly related to https://github.com/xmtp-labs/converse-app/issues/365

**Comment by insipx** [comment]
[Make NoChanges NoOp #927](https://github.com/xmtp/libxmtp/pull/927) should fix this, closing f or now
