### ISSUE TITLE
Feature request: sync all function that syncs the list of groups and the messages of each group for a given libxmtp client/inboxID

### ISSUE THREAD

**Issue by cameronvoell** [xmtp/libxmtp#934]
### Is your feature request related to a problem?

Inbox app devs report difficulties syncing all groups for a given client without experiencing unexpected or intermittent failures or performance issue. Doing this on the libxmtp side could lead to performance and reliability gains.

**Comment by insipx** [comment]
I think #981 and #992 fix this?
