### ISSUE TITLE
Error: LibXMTP.GenericError.GroupError(message: "Group error: Errors occurred during sync [Client(KeyPac...

### ISSUE THREAD

**Issue by nplasterer** [xmtp/libxmtp#947]
Sentry Issue: [CONVERSE-REACT-NATIVE-18J](https://converse-app.sentry.io/issues/5592194575/?referrer=github_integration)

```
Error: LibXMTP.GenericError.GroupError(message: "Group error: Errors occurred during sync [Client(KeyPackageVerification(TlsError(EndOfStream)))]")
  at _callSuper (app:///main.jsbundle:6:38)
...
(2 additional frame(s) were not displayed)
```

**Comment by neekolas** [comment]
I looked at the DB today. There are no empty key packages stored in there. But I figured out what is happening on the nodes to make it seem like there are empty key packages. There is some weird code in the API that will leave empty results when you request key packages for an installation that doesn't exist.

I have a fix that will make the error handling clearer (although maybe it's stricter than we want). The bigger problem is that we have installations that exist as identity updates, but don't actually have any key packages. It feels like we should bundle both of those things together, which will require an API change.

**Comment by nplasterer** [comment]
Preventing this from happening going forward should be resolved. However we need to think about how to fix this for existing clients that are stuck in this state. The KeyPackage expiration could help this long term but may introduce other bugs. Is there a way we could do a one time clean up to remove installations that might be in this state? @neekolas

**Comment by nplasterer** [comment]
**Revoke past installations**


- Rotate inbox ids
- Revert ignore empty keypackages
- Rotate keypackages (ignore expiration)

**Comment by nplasterer** [comment]
Will be fixed by retro actively fixed by this issue https://github.com/xmtp/libxmtp/issues/974. And then we can hard control it at the API level.

**Comment by insipx** [comment]
Closing for now seeing as #974 has been merged and we all updated to 249.
