### ISSUE TITLE
Storage(DieselResult(DatabaseError(UniqueViolation, "UNIQUE constraint failed: group_messages.id")))

### ISSUE THREAD

**Issue by nplasterer** [xmtp/libxmtp#957]
These errors aren't harmful but noisy lets ignore them.

**Comment by nplasterer** [comment]
Reproducable in this test
https://github.com/xmtp/xmtp-react-native/pull/457/files#r1712337925

**Comment by nplasterer** [comment]
Maybe we should also surface errors in streams better?

**Comment by insipx** [comment]
> Maybe we should also surface errors in streams better?

#899 

Shouldn't be too difficult to do this, just requires playing around with the ffi barrier and rust `Error` types

**Comment by nplasterer** [comment]
So we have to error `Error so OpenMLS db transaction are rolled back on duplicate welcomes` just going to close this out and we can ignore these in logs and sentry.
