### ISSUE TITLE
use `cargo nextest` in CI instead of `cargo test`

### ISSUE THREAD

**Issue by insipx** [xmtp/libxmtp#999]
`cargo nextest` is superior to `cargo test` in pretty much every way. Now that we have lots of tests, makes sense to switch over and should speed up our CI a bit. Also, the output into std is much better, and nextest contains auto-detection for flaky test, auto-retries flaky tests, + flags 'slow' tests. Also has configurable timeouts, etc.

Website: https://nexte.st/

**Comment by Arya-A-Nair** [comment]
Hey, I am a rust developer and also ETHINDIA 2023 winner. Can I be assigned to this issue?

**Comment by insipx** [comment]
Sure!

**Comment by Arya-A-Nair** [comment]
Hey @insipx can you just let me know which files I would have to update to do the migration?

**Comment by Arya-A-Nair** [comment]
Hey i have made a PR for the same - [1093](https://github.com/xmtp/libxmtp/pull/1093)

**Comment by insipx** [comment]
Closed by #1093
